### ISSUE TITLE
触发器与存储过程讲义 | Leeyom的个人站

### ISSUE THREAD

**Issue by wangleeyom** [wangleeyom/wangleeyom.github.io#57]
http://leeyom.top/2017/04/27/tech-trigger-procedure-note/

**Comment by ibubbo** [comment]
触发器就是一个特殊的存储过程，不过在实际开发过程中，存储过程也用的偏少，原因是后端开发人员本身就是兼职着进行数据库操作，很少有专门的数据库人员去对存储过程进行维护和管理，其次灵活性不够高，项目需求变更的很快，每次变更都要修改存储过程。
这是个人见解0.0

**Comment by wangleeyom** [comment]
@ibubbo 阿里巴巴的开发手册：禁止使用存储过程，存储过程难以调试和扩展，更没有移植性。存储过程和触发器能避免尽量避免吧。
