### ISSUE TITLE
关于前后端分离的思考和总结 | Leeyom的个人站

### ISSUE THREAD

**Issue by wangleeyom** [wangleeyom/wangleeyom.github.io#72]
http://leeyom.top/2017/11/04/fontend-backend-separation/

**Comment by liuzhongpo** [comment]
如果只是单纯的前后端分离开发，和你说的差不多。但是针对整体来说，一套 restful-API是否能适应移动端、PC端。是否需要前后端共同商定好数据接口的交互形式和数据格式，以及前后台的职责划分，比如图片上传与下载是否需要经过后台处理？后台接口开发慢，是否需要套用mock server？ 等等一大堆问题。

**Comment by wangleeyom** [comment]
@liuzhongpo  这里只是说的一个比较基础的，并且通用的restful API接口平台，主要针对web端，如果要配合移动端，多平台的话，还有很多细节是需要深究的😁
