### ISSUE TITLE
关于ubuntu虚拟机问题小记 | Leeyom的个人站

### ISSUE THREAD

**Issue by wangleeyom** [wangleeyom/wangleeyom.github.io#74]
http://leeyom.top/2017/11/09/Ubuntu-virtual-problem/

**Comment by Waiter-Iris** [comment]
你好。请问一下。hexo博客简单完成后如何添加新博客呢？我也是今年入Java行业的新人，请多关照。

**Comment by wangleeyom** [comment]
@Waiter-Iris ,采用命令`hexo new "文章标题"`，即可创建一篇文章，互相学习。
